### ISSUE TITLE
Update libraries

### ISSUE THREAD

**Issue by JonasWanke** [schul-cloud/schulcloud-mobile-android#103]
Update RxJava/RxAndroid to version 2, Gradle to version 4 (removes the need for Retrolambda) and Firebase from version 9 to 11.

**Comment by kremer-io** [comment]
@JonasWanke Pls provide further details. Which libraries, why .. ?

**Comment by JonasWanke** [comment]
@kremer-io The main intention was to update RxJava/RxAndroid [to version 2](https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0), Gradle to version 4 ([removes the need for Retrolambda](https://developer.android.com/studio/write/java8-support.html)) and Firebase from version 9 to 11.

**Comment by kremer-io** [comment]
@JonasWanke Thx, I've updated the description.

**Comment by JonasWanke** [comment]
Irrelevant for now b/c of the new app version
