### ISSUE TITLE
Add password recovery

### ISSUE THREAD

**Issue by JonasWanke** [schul-cloud/schulcloud-mobile-android#109]

**Comment by Araknor99** [comment]
This issue still needs quite some work ( At least in my perspective.), since the password recovery button only leads you to the schulcloud web page.

Would you mind telling me why you are asking?

**Comment by MarvinFischer** [comment]
Because this issue was created in December and I have not found anything in the master-code yet. If there is still the need I would start to create an extra activity for the recovery function.

**Comment by Araknor99** [comment]
It would be good to have a password recovery as some users tend to forget their password more often. So go ahead.
