### ISSUE TITLE
Fragment navigation doesn't work after configuration changes

### ISSUE THREAD

**Issue by JonasWanke** [schul-cloud/schulcloud-mobile-android#110]
`addFragment()` doesn't work after a configuration change. The problem is that MainPresenter keeps references to the old fragments even after recreation and therefore doesn't find the parent.

**Comment by kremer-io** [comment]
@JonasWanke Could you give further details? Maybe some code snippets?

**Comment by JonasWanke** [comment]
I could, but I have already developed a working solution for another app which I'm currently testing. I will include it in this app as soon as I'm sure it works.
