### ISSUE TITLE
Remove keystores from git

### ISSUE THREAD

**Issue by tobiasrohloff** [schul-cloud/schulcloud-mobile-android#56]
Under https://github.com/schul-cloud/schulcloud-mobile-android/blob/master/app/keystore/ the debug and release keystores are checked into git.

Even if the apk signing still requires two passwords, this file should not be public!

There is also no need for providing the debug keystore. Any developer can use the default local one and debug builds can be shared as well.

**Comment by pinussilvestrus** [comment]
Thanks, I will move this to our Trello-Board

**Comment by JonasWanke** [comment]
Should be fixed with the new version. Otherwise please reopen the issue on Jira.
