### ISSUE TITLE
Use Travis to build and deploy the app

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schulcloud-mobile-android#6]
I would like to try out the app and when I develop it, see how to set it up.

Therefore, I would like to see travis building the app.

- [ ] build the app with travis (How is this done?)
- [ ] add upload to github releases (I can do this)

What do you think?

**Comment by pinussilvestrus** [comment]
There is also a Trello Board for this: SchulCloud Mobile - https://trello.com/b/vKSOPiru/schulcloud-mobile.
And there is a ticket for CI, but we do not have time for this: https://trello.com/c/9d44KbfI/7-explore-test-environment

Feel free to contribute!

**Comment by niccokunzmann** [comment]
If you give me the build script, I can take care of the rest.

**Comment by pinussilvestrus** [comment]
I've started to configure travis on this branch: https://github.com/schul-cloud/schulcloud-mobile-android/tree/7-explore-test-environment, but there are several issues with licenses and I took it back. Maybe you have some ideas. The build script is the standard android `./gradlew build`, the test command ist `./gradlew connectedCheck` or `./gradlew test`, the second would also run the [checkstyle](http://checkstyle.sourceforge.net/) command, which is interesting for code style.

**Comment by niccokunzmann** [comment]
What is the content of your licenses directory?
%ANDROID_HOME%\licenses

**Comment by pinussilvestrus** [comment]
@niccokunzmann I solved it :) I'm no getting issues with our encrypted secrets, but I'm on it ;)

**Comment by pinussilvestrus** [comment]
I close this issue because It's almost done by myself and there's a better explained trello ticket for it.

**Comment by niccokunzmann** [comment]
I would like to leave the issue open until I downloaded the apk file from the [releases](https://github.com/schul-cloud/schulcloud-mobile-android/releases). Please re-open the issue.
