### ISSUE TITLE
Create beta play store release

### ISSUE THREAD

**Issue by pinussilvestrus** [schul-cloud/schulcloud-mobile-android#61]
- [ ] play store einstellungen
- [x] keystore file
- [x] play store account

**Comment by pinussilvestrus** [comment]
@jprberlin Habe jetzt alle Berechtigungen von den Admins bekommen. Wenn wir ein Logo haben, könnten wir quasi mal einen Alpha-Release rausgeben.

**Comment by jprberlin** [comment]
Supi.. Logo sollte in Kürze da sein.

**Comment by pinussilvestrus** [comment]
@jprberlin wie ist der Stand jetzt? Logo habe ich hochgeladen, wenn wollen wir was veröffentlichen?

**Comment by jprberlin** [comment]
Bitte (Beta)-Release vorbereiten. Der Crash den Elias beobachtet hat sollte noch geklärt werden, dann können wir das (Beta)-Releasen. Bitte wegen Marketingtexten mit Catrina und Max abstimmen.
